function xd = fg_chua(in1)
%FG_CHUA
%    XD = FG_CHUA(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    28-Mar-2024 00:57:10

u = in1(1,:);
x1 = in1(2,:);
x2 = in1(3,:);
x3 = in1(4,:);
xd = [x1.*(2.08e+2./1.25e+2)+x2.*(5.2e+1./5.0)-x1.^3.*4.264e-1;u+x1-x2+x3;x2.*(-3.3e+1./2.0)];
