function ff = fg_chua(u,x1,x2,x3)
%FG_CHUA
%    FF = FG_CHUA(U,X1,X2,X3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    26-Mar-2024 14:27:27

ff = [x1.*(1.0e+1./7.0)+x2.*1.0e+1-x1.^3.*(2.0e+1./7.0);u+x1-x2+x3;x2.*(-1.0e+2./7.0)];
